# Generated by Django 3.0.3 on 2020-08-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200828_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frameworks',
            new_name='Framework',
        ),
        migrations.RenameModel(
            old_name='ITConstructs',
            new_name='ITConstruct',
        ),
    ]
