# Generated by Django 3.0.3 on 2020-08-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200828_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='pdf/MyResume')),
            ],
        ),
    ]
