# Generated by Django 3.0.3 on 2020-08-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_myresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=15)),
                ('choice1', models.CharField(blank=True, max_length=15)),
                ('choice2', models.CharField(blank=True, max_length=15)),
                ('choice3', models.CharField(blank=True, max_length=15)),
                ('image1', models.ImageField(upload_to='images/explore/')),
                ('image2', models.ImageField(upload_to='images/explore/')),
            ],
        ),
    ]
