# Generated by Django 3.0.3 on 2020-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_explore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='choice1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='explore',
            name='choice2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='explore',
            name='choice3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
