# Generated by Django 3.0.3 on 2020-08-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200831_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
