# Generated by Django 3.0.3 on 2020-08-31 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200831_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='endDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
