# Generated by Django 3.0.3 on 2020-08-31 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200831_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='endDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
