# Generated by Django 3.0.3 on 2020-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200831_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
