# Generated by Django 3.0.3 on 2020-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_project_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='images/Blog/')),
                ('link', models.URLField()),
            ],
        ),
    ]
